name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run test
      - name: create .env file
        run: |
          echo "${{ secrets.TEST }}" >> .env
      - name: Deploy to AWS
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-dotenv-plugin && serverless deploy"
          entrypoint: /bin/sh
    env:
      TEST: ${{ secrets.TEST }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
